name: deploy to mixhost
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'kenya0411/customers'
      - name: ssh key generate
        run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.MIXHOST_SECRET_KEY }} #githubに登録したmixhostへの秘密鍵を指定
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avz --delete
          path: ./ #mixhostに送りたいファイルのあるパスを指定
          remote_path: /home/${{ secrets.MIXHOST_USERNAME }}/public_html/site/customers #mixhostのどこに同期させるか
          remote_host: ${{ secrets.MIXHOST_HOSTNAME }}
          remote_user: ${{ secrets.MIXHOST_USERNAME }}
          remote_port: 22
          remote_key: ${{ secrets.MIXHOST_SECRET_KEY }}
 