name: SSH Connection Test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print SSH key
        run: echo "$SSH_PRIVATE_KEY"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.MIXHOST_SECRET_KEY }} 