name: SSH Connection Test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.MIXHOST_SECRET_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.MIXHOST_HOSTNAME }} >> ~/.ssh/known_hosts
      - name: SSH and run
        run: |
          ssh ${{ secrets.MIXHOST_USERNAME }}@${{ secrets.MIXHOST_HOSTNAME }} "echo 'Hello, World!'"
 　